//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommerceFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Produtos = new HashSet<Produtos>();
        }
    
        public int IdCategoria { get; set; }
        public string NomeCategoria { get; set; }
    
        public virtual ICollection<Produtos> Produtos { get; set; }
    }
}
