//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommerceFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public Pedidos()
        {
            this.ItensPedido = new HashSet<ItensPedido>();
        }
    
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> DataPedido { get; set; }
        public string Status { get; set; }
        public decimal ValorTotal { get; set; }
    
        public virtual ICollection<ItensPedido> ItensPedido { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
