//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommerceFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        public Produtos()
        {
            this.ItensPedido = new HashSet<ItensPedido>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public string Descricao { get; set; }
        public string Imagem { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public int Estoque { get; set; }
        public string Disponibilidade { get; set; }
        public Nullable<int> CategoriaId { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual ICollection<ItensPedido> ItensPedido { get; set; }
    }
}
